blank_issues_enabled: false
contact_links:
  - name: Plugin Documentation
    url: https://vite.pw/docs
    about: Official plugin documentation.
  - name: Questions & Discussions
    url: https://processwire.com/talk
    about: Use ProcessWire support thread for message-board style questions and discussions.
